version: '2'
services:
  rails: &app_base
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
    env_file:
      - "./.env.dev"
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=webpack"
    volumes:
      - ".:/app"
    volumes_from:
      - data
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpack:
    <<: *app_base
    command: "bin/webpack-dev-server"
    environment:
      - "WEBPACKER_DEV_SERVER_HOST=0.0.0.0"
    ports:
      - "3035:3035"
    depends_on:
      - rails
    tty: false
    stdin_open: false
  db:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: "mysql:8.0.29"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes_from:
      - data
    ports:
      - "3306:3306"
  data:
    image: "busybox"
    volumes:
      - "db:/var/lib/mysql"
      - "bundle:/usr/local/bundle"

volumes:
  db:
    driver: local
  bundle:
    driver: local
