#!/usr/bin/env bash

set -e

cp .env.dev.sample .env.dev

docker-compose build

docker-compose run --rm rails bundle exec rails new . --force --database=mysql --webpack=vue --skip-turbolinks --skip-action-mailer --skip-action-mailbox --skip-active-storage --skip-git

cp -f template/database.yml config/database.yml

docker-compose run --rm rails bundle exec spring binstub --all
